In [1]:
import numpy as np

In [2]:
a = [0.1 , 0.3 , 0.6 , 0.5]
a = np.array(a)
a

array([0.1, 0.3, 0.6, 0.5])

In [3]:
1 - a

array([0.9, 0.7, 0.4, 0.5])

In [4]:
np.prod(a)

0.009

 given p1 , p2 .... pn ; p(n+1) = product(1-pi)
 
 new probailities => 
 
 p\`1 = p1 / (1+p(n+1)) 
 

In [16]:
def new_probailities_set(prob):
    prob = np.array(prob)
    newp = np.prod(1-prob)
    prob = prob/(1+newp) ## for existing probabilty
    newp = newp/(1+newp)
    prob = np.append(prob,newp)
    return prob

In [17]:
a = [0.1 , 0.3 , 0.6 , 0.5]
a = np.array(a)
type(a)

numpy.ndarray

In [18]:
a

array([0.1, 0.3, 0.6, 0.5])

In [19]:
new_probailities_set(a)

array([0.08880995, 0.26642984, 0.53285968, 0.44404973, 0.11190053])